(in-package :aio.error)

(defun str (error-code)
  (sb-int:strerror error-code))

(defconstant PERM 1 "Operation not permitted") 
(defconstant NOEN 2 "No such file or directory") 
(defconstant SRCH 3 "No such process") 
(defconstant INTR 4 "Interrupted system call") 
(defconstant IO 5 "I/O error") 
(defconstant NXIO 6 "No such device or address") 
(defconstant 2BIG 7 "Argument list too long") 
(defconstant NOEXEC 8 "Exec format error") 
(defconstant BADF 9 "Bad file number") 
(defconstant CHILD 10 "No child processes") 
(defconstant AGAIN 11 "Try again") 
(defconstant NOMEM 12 "Out of memory") 
(defconstant ACCES 13 "Permission denied") 
(defconstant FAULT 14 "Bad address") 
(defconstant NOTBLK 15 "Block device required") 
(defconstant BUSY 16 "Device or resource busy") 
(defconstant EXIST 17 "File exists") 
(defconstant XDEV 18 "Cross-device link") 
(defconstant NODEV 19 "No such device") 
(defconstant NOTDIR 20 "Not a directory") 
(defconstant ISDIR 21 "Is a directory") 
(defconstant INVAL 22 "Invalid argument") 
(defconstant NFILE 23 "File table overflow") 
(defconstant MFILE 24 "Too many open files") 
(defconstant NOTTY 25 "Not a typewriter") 
(defconstant TXTBSY 26 "Text file busy") 
(defconstant FBIG 27 "File too large") 
(defconstant NOSPC 28 "No space left on device") 
(defconstant SPIPE 29 "Illegal seek") 
(defconstant ROFS 30 "Read-only file system") 
(defconstant MLINK 31 "Too many links") 
(defconstant PIPE 32 "Broken pipe") 
(defconstant DOM 33 "Math argument out of domain of func") 
(defconstant RANGE 34 "Math result not representable") 
(defconstant DEADLK 35 "Resource deadlock would occur") 
(defconstant NAMETOOLONG 36 "File name too long") 
(defconstant NOLCK 37 "No record locks available") 
(defconstant NOSYS 38 "Function not implemented") 
(defconstant NOTEMPTY 39 "Directory not empty") 
(defconstant LOOP 40 "Too many symbolic links encountered") 
(defconstant WOULDBLOCK AGAIN "Operation would block") 
(defconstant NOMSG 42 "No message of desired type") 
(defconstant IDRM 43 "Identifier removed") 
(defconstant CHRNG 44 "Channel number out of range") 
(defconstant L2NSYNC 45 "Level 2 not synchronized") 
(defconstant L3HLT 46 "Level 3 halted") 
(defconstant L3RST 47 "Level 3 reset") 
(defconstant LNRNG 48 "Link number out of range") 
(defconstant UNATCH 49 "Protocol driver not attached") 
(defconstant NOCSI 50 "No CSI structure available") 
(defconstant L2HLT 51 "Level 2 halted") 
(defconstant BADE 52 "Invalid exchange") 
(defconstant BADR 53 "Invalid request descriptor") 
(defconstant XFULL 54 "Exchange full") 
(defconstant NOANO 55 "No anode") 
(defconstant BADRQC 56 "Invalid request code") 
(defconstant BADSLT 57 "Invalid slot") 
(defconstant DEADLOCK DEADLK "Resource deadlock would occur")
(defconstant BFONT 59 "Bad font file format") 
(defconstant NOSTR 60 "Device not a stream") 
(defconstant NODATA 61 "No data available") 
(defconstant TIME 62 "Timer expired") 
(defconstant NOSR 63 "Out of streams resources") 
(defconstant NONET 64 "Machine is not on the network") 
(defconstant NOPKG 65 "Package not installed") 
(defconstant REMOTE 66 "Object is remote") 
(defconstant NOLINK 67 "Link has been severed") 
(defconstant ADV 68 "Advertise error") 
(defconstant SRMNT 69 "Srmount error") 
(defconstant COMM 70 "Communication error on send") 
(defconstant PROTO 71 "Protocol error") 
(defconstant MULTIHOP 72 "Multihop attempted") 
(defconstant DOTDOT 73 "RFS specific error") 
(defconstant BADMSG 74 "Not a data message") 
(defconstant OVERFLOW 75 "Value too large for defined data type") 
(defconstant NOTUNIQ 76 "Name not unique on network") 
(defconstant BADFD 77 "File descriptor in bad state") 
(defconstant REMCHG 78 "Remote address changed") 
(defconstant LIBACC 79 "Can not access a needed shared library") 
(defconstant LIBBAD 80 "Accessing a corrupted shared library") 
(defconstant LIBSCN 81 ".lib section in a.out corrupted") 
(defconstant LIBMAX 82 "Attempting to link in too many shared libraries") 
(defconstant LIBEXEC 83 "Cannot exec a shared library directly") 
(defconstant ILSEQ 84 "Illegal byte sequence") 
(defconstant RESTART 85 "Interrupted system call should be restarted") 
(defconstant STRPIPE 86 "Streams pipe error") 
(defconstant USERS 87 "Too many users") 
(defconstant NOTSOCK 88 "Socket operation on non-socket") 
(defconstant DESTADDRREQ 89 "Destination address required") 
(defconstant MSGSIZE 90 "Message too long") 
(defconstant PROTOTYPE 91 "Protocol wrong type for socket") 
(defconstant NOPROTOOPT 92 "Protocol not available") 
(defconstant PROTONOSUPPORT 93 "Protocol not supported") 
(defconstant SOCKTNOSUPPORT 94 "Socket type not supported") 
(defconstant OPNOTSUPP 95 "Operation not supported on transport endpoint") 
(defconstant PFNOSUPPORT 96 "Protocol family not supported") 
(defconstant AFNOSUPPORT 97 "Address family not supported by protocol") 
(defconstant ADDRINUSE 98 "Address already in use") 
(defconstant ADDRNOTAVAIL 99 "Cannot assign requested address") 
(defconstant NETDOWN 100 "Network is down") 
(defconstant NETUNREACH 101 "Network is unreachable") 
(defconstant NETRESET 102 "Network dropped connection because of reset") 
(defconstant CONNABORTED 103 "Software caused connection abort") 
(defconstant CONNRESET 104 "Connection reset by peer") 
(defconstant NOBUFS 105 "No buffer space available") 
(defconstant ISCONN 106 "Transport endpoint is already connected") 
(defconstant NOTCONN 107 "Transport endpoint is not connected") 
(defconstant SHUTDOWN 108 "Cannot send after transport endpoint shutdown") 
(defconstant TOOMANYREFS 109 "Too many references: cannot splice") 
(defconstant TIMEDOUT 110 "Connection timed out") 
(defconstant CONNREFUSED 111 "Connection refused") 
(defconstant HOSTDOWN 112 "Host is down") 
(defconstant HOSTUNREACH 113 "No route to host") 
(defconstant ALREADY 114 "Operation already in progress") 
(defconstant INPROGRESS 115 "Operation now in progress") 
(defconstant STALE 116 "Stale NFS file handle") 
(defconstant UCLEAN 117 "Structure needs cleaning") 
(defconstant NOTNAM 118 "Not a XENIX named type file") 
(defconstant NAVAIL 119 "No XENIX semaphores available") 
(defconstant ISNAM 120 "Is a named type file") 
(defconstant REMOTEIO 121 "Remote I/O error") 
(defconstant DQUOT 122 "Quota exceeded") 
(defconstant NOMEDIUM 123 "No medium found") 
(defconstant MEDIUMTYPE 124 "Wrong medium type") 
(defconstant CANCELED 125 "Operation Canceled") 
(defconstant NOKEY 126 "Required key not available") 
(defconstant KEYEXPIRED 127 "Key has expired") 
(defconstant KEYREVOKED 128 "Key has been revoked") 
(defconstant KEYREJECTED 129 "Key was rejected by service") 
(defconstant OWNERDEAD 130 "Owner died") 
(defconstant NOTRECOVERABLE 131 "State not recoverable") 
(defconstant RFKILL 132 "Operation not possible due to RF-kill")
